spring.application.name=ms-usuarios
server.port=8082

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (SUPABASE)
# ==========================================
spring.datasource.url=jdbc:postgresql://db.rizihfwsylfpjfpbnmah.supabase.co:5432/postgres?currentSchema=schema_usuarios&pgbouncer=true
spring.datasource.username=postgres
spring.datasource.password=iHOLzaJ0eH606T9h
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA Configuration
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ==========================================
# CONFIGURACIÓN EUREKA & SEGURIDAD
# ==========================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Descarga de llaves públicas para validar JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081