# ==========================================
# CONFIGURACIÓN GENERAL
# ==========================================
spring.application.name=auth
server.port=8081

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (SUPABASE)
# ==========================================
spring.datasource.url=jdbc:postgresql://db.rizihfwsylfpjfpbnmah.supabase.co:5432/postgres?currentSchema=schema_usuarios&pgbouncer=true
spring.datasource.username=postgres
spring.datasource.password=iHOLzaJ0eH606T9h
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true