spring.application.name=ms-notificaciones
server.port=8085

# ==========================================
# CONEXIÓN A SUPABASE
# ==========================================
spring.datasource.url=jdbc:postgresql://db.rizihfwsylfpjfpbnmah.supabase.co:5432/postgres?currentSchema=schema_notificaciones&pgbouncer=true
spring.datasource.username=postgres
spring.datasource.password=iHOLzaJ0eH606T9h
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ==========================================
# CONFIGURACIÓN EUREKA & SEGURIDAD
# ==========================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081