spring.application.name=ms-core
server.port=8083

# ==========================================
# CONEXIÓN A SUPABASE
# ==========================================
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?currentSchema=schema_core&pgbouncer=true&prepareThreshold=0
spring.datasource.username=postgres.rizihfwsylfpjfpbnmah
spring.datasource.password=iHOLzaJ0eH606T9h
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ==========================================
# CONFIGURACIÓN EUREKA & SEGURIDAD
# ==========================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081